### ISSUE TITLE
Readme.md is not up to date

### ISSUE THREAD

**Issue by c-pid** [njaremko/iota-lib-rs#2]
The minimal example in the readme.md is not up to date. It uses ``send_transfer`` instead of ``send_transfers``. Further the method is missing an argument.

It would be nice if you can fix it, since I am a rust newb and can't get it to work myself. Thank you!

**Comment by njaremko** [comment]
Whoops. Totally forgot about that. Fixing now.

**Comment by njaremko** [comment]
Fixed. 

Documentation can be found here: https://docs.rs/iota-lib-rs/

If you have any questions, feel free to contact me on keybase or discord (iota server) in the rust or development chats.
